# coding: utf-8

"""
    Jaap Counter

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class JaapcountersApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_counter_by_name(self, formname, **kwargs):  # noqa: E501
        """Get existing jaap counter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_counter_by_name(formname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str formname: (required)
        :return: Rows
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_counter_by_name_with_http_info(formname, **kwargs)  # noqa: E501
        else:
            (data) = self.get_counter_by_name_with_http_info(formname, **kwargs)  # noqa: E501
            return data

    def get_counter_by_name_with_http_info(self, formname, **kwargs):  # noqa: E501
        """Get existing jaap counter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_counter_by_name_with_http_info(formname, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str formname: (required)
        :return: Rows
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['formname']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_counter_by_name" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'formname' is set
        if ('formname' not in params or
                params['formname'] is None):
            raise ValueError("Missing the required parameter `formname` when calling `get_counter_by_name`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'formname' in params:
            query_params.append(('formname', params['formname']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/jaapcounters', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Rows',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def submit_new_counter(self, formname, number, **kwargs):  # noqa: E501
        """Submit new jaap counter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.submit_new_counter(formname, number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str formname: (required)
        :param float number: (required)
        :param str title:
        :param str description:
        :return: Result
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.submit_new_counter_with_http_info(formname, number, **kwargs)  # noqa: E501
        else:
            (data) = self.submit_new_counter_with_http_info(formname, number, **kwargs)  # noqa: E501
            return data

    def submit_new_counter_with_http_info(self, formname, number, **kwargs):  # noqa: E501
        """Submit new jaap counter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.submit_new_counter_with_http_info(formname, number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str formname: (required)
        :param float number: (required)
        :param str title:
        :param str description:
        :return: Result
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['formname', 'number', 'title', 'description']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method submit_new_counter" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'formname' is set
        if ('formname' not in params or
                params['formname'] is None):
            raise ValueError("Missing the required parameter `formname` when calling `submit_new_counter`")  # noqa: E501
        # verify the required parameter 'number' is set
        if ('number' not in params or
                params['number'] is None):
            raise ValueError("Missing the required parameter `number` when calling `submit_new_counter`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'formname' in params:
            query_params.append(('formname', params['formname']))  # noqa: E501
        if 'number' in params:
            query_params.append(('number', params['number']))  # noqa: E501
        if 'title' in params:
            query_params.append(('title', params['title']))  # noqa: E501
        if 'description' in params:
            query_params.append(('description', params['description']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/submitjaapcounters', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Result',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_jaap_details(self, jaap_details, **kwargs):  # noqa: E501
        """Update jaap counter fields  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_jaap_details(jaap_details, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param JaapDetails jaap_details: (required)
        :return: UpdatedRows
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_jaap_details_with_http_info(jaap_details, **kwargs)  # noqa: E501
        else:
            (data) = self.update_jaap_details_with_http_info(jaap_details, **kwargs)  # noqa: E501
            return data

    def update_jaap_details_with_http_info(self, jaap_details, **kwargs):  # noqa: E501
        """Update jaap counter fields  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_jaap_details_with_http_info(jaap_details, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param JaapDetails jaap_details: (required)
        :return: UpdatedRows
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['jaap_details']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_jaap_details" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'jaap_details' is set
        if ('jaap_details' not in params or
                params['jaap_details'] is None):
            raise ValueError("Missing the required parameter `jaap_details` when calling `update_jaap_details`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'jaap_details' in params:
            query_params.append(('jaapDetails', params['jaap_details']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/submitjaapdeets', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='UpdatedRows',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
