version:  '3.5'

services:
  gurmat_bot:
    image: gurmat-bot:1
    build: './'
    container_name: 'gurmat-bot'
    labels:
      description: 'Gurmat Bot for Sikh Discord'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./src:/gurmat-bot/src"
    entrypoint: "python src/main.py"
