version:  '3.5'

services:

  gurmat-bot:
    image: gurmat-bot:1
    build: './'
    container_name: 'gurmat-bot'
    labels:
      description: 'Gurmat Bot for Sikh Discord'
    volumes:
      - "./src:/gurmat-bot/src:Z"
    entrypoint: "python src/main.py"
