# coding: utf-8

"""
    Jaap Counter

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Counter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'formname': 'str',
        'jaaps': 'str',
        'title': 'str',
        'description': 'str',
        'lastmod': 'datetime'
    }

    attribute_map = {
        'formname': 'formname',
        'jaaps': 'jaaps',
        'title': 'title',
        'description': 'description',
        'lastmod': 'lastmod'
    }

    def __init__(self, formname=None, jaaps=None, title=None, description=None, lastmod=None):  # noqa: E501
        """Counter - a model defined in Swagger"""  # noqa: E501
        self._formname = None
        self._jaaps = None
        self._title = None
        self._description = None
        self._lastmod = None
        self.discriminator = None
        if formname is not None:
            self.formname = formname
        if jaaps is not None:
            self.jaaps = jaaps
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if lastmod is not None:
            self.lastmod = lastmod

    @property
    def formname(self):
        """Gets the formname of this Counter.  # noqa: E501


        :return: The formname of this Counter.  # noqa: E501
        :rtype: str
        """
        return self._formname

    @formname.setter
    def formname(self, formname):
        """Sets the formname of this Counter.


        :param formname: The formname of this Counter.  # noqa: E501
        :type: str
        """

        self._formname = formname

    @property
    def jaaps(self):
        """Gets the jaaps of this Counter.  # noqa: E501


        :return: The jaaps of this Counter.  # noqa: E501
        :rtype: str
        """
        return self._jaaps

    @jaaps.setter
    def jaaps(self, jaaps):
        """Sets the jaaps of this Counter.


        :param jaaps: The jaaps of this Counter.  # noqa: E501
        :type: str
        """

        self._jaaps = jaaps

    @property
    def title(self):
        """Gets the title of this Counter.  # noqa: E501


        :return: The title of this Counter.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Counter.


        :param title: The title of this Counter.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this Counter.  # noqa: E501


        :return: The description of this Counter.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Counter.


        :param description: The description of this Counter.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def lastmod(self):
        """Gets the lastmod of this Counter.  # noqa: E501


        :return: The lastmod of this Counter.  # noqa: E501
        :rtype: datetime
        """
        return self._lastmod

    @lastmod.setter
    def lastmod(self, lastmod):
        """Sets the lastmod of this Counter.


        :param lastmod: The lastmod of this Counter.  # noqa: E501
        :type: datetime
        """

        self._lastmod = lastmod

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Counter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Counter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
