# coding: utf-8

"""
    Jaap Counter

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JaapDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'condition': 'JaapDetailsCondition',
        'set': 'JaapDetailsSet'
    }

    attribute_map = {
        'condition': 'condition',
        'set': 'set'
    }

    def __init__(self, condition=None, set=None):  # noqa: E501
        """JaapDetails - a model defined in Swagger"""  # noqa: E501
        self._condition = None
        self._set = None
        self.discriminator = None
        if condition is not None:
            self.condition = condition
        if set is not None:
            self.set = set

    @property
    def condition(self):
        """Gets the condition of this JaapDetails.  # noqa: E501


        :return: The condition of this JaapDetails.  # noqa: E501
        :rtype: JaapDetailsCondition
        """
        return self._condition

    @condition.setter
    def condition(self, condition):
        """Sets the condition of this JaapDetails.


        :param condition: The condition of this JaapDetails.  # noqa: E501
        :type: JaapDetailsCondition
        """

        self._condition = condition

    @property
    def set(self):
        """Gets the set of this JaapDetails.  # noqa: E501


        :return: The set of this JaapDetails.  # noqa: E501
        :rtype: JaapDetailsSet
        """
        return self._set

    @set.setter
    def set(self, set):
        """Sets the set of this JaapDetails.


        :param set: The set of this JaapDetails.  # noqa: E501
        :type: JaapDetailsSet
        """

        self._set = set

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JaapDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JaapDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
