# coding: utf-8

"""
    Jaap Counter

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdatedRows(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total_updated_rows': 'float'
    }

    attribute_map = {
        'total_updated_rows': 'totalUpdatedRows'
    }

    def __init__(self, total_updated_rows=None):  # noqa: E501
        """UpdatedRows - a model defined in Swagger"""  # noqa: E501
        self._total_updated_rows = None
        self.discriminator = None
        if total_updated_rows is not None:
            self.total_updated_rows = total_updated_rows

    @property
    def total_updated_rows(self):
        """Gets the total_updated_rows of this UpdatedRows.  # noqa: E501


        :return: The total_updated_rows of this UpdatedRows.  # noqa: E501
        :rtype: float
        """
        return self._total_updated_rows

    @total_updated_rows.setter
    def total_updated_rows(self, total_updated_rows):
        """Sets the total_updated_rows of this UpdatedRows.


        :param total_updated_rows: The total_updated_rows of this UpdatedRows.  # noqa: E501
        :type: float
        """

        self._total_updated_rows = total_updated_rows

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdatedRows, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdatedRows):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
