openapi: 3.0.1

info:
  title: Jaap Counter
  version: 1.0.0

servers:
- url: https://api.manjotsingh.xyz/

tags:
- name: jaapcounters
  description: Retrieve and submit jaap counters

paths:
  /jaapcounters:
    get:
      tags:
      - jaapcounters
      summary: Get existing jaap counter
      operationId: getCounterByName
      parameters:
      - name: formname
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rows'

  /submitjaapcounters:
    post:
      tags:
      - jaapcounters
      summary: Submit new jaap counter
      operationId: submitNewCounter
      parameters:
      - name: formname
        in: query
        required: true
        schema:
          type: string
      - name: number
        in: query
        required: true
        schema:
          type: number
      - name: title
        in: query
        required: false
        schema:
          type: string
      - name: description
        in: query
        required: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'

  /submitjaapdeets:
    put:
      tags:
      - jaapcounters
      summary: Update jaap counter fields
      operationId: updateJaapDetails
      parameters:
        - name: jaapDetails
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/JaapDetails'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdatedRows'

components:
  schemas:
    Rows:
      type: object
      properties:
        rows:
          type: array
          items:
            $ref: '#/components/schemas/Counter'

    Counter:
      type: object
      properties:
        formname:
          type: string
        jaaps:
          type: string
        title:
          type: string
        description:
          type: string
        lastmod:
          type: string
          format: date-time
        goal:
          type: string


    JaapDetails:
      type: object
      properties:
        condition:
          type: object
          properties:
            formname:
              type: string
        set:
          properties:
            title:
              type: string
            description:
              type: string
            goal:
              type: number

    Result:
      type: object
      properties:
        result:
          type: string
        row:
          type: number

    UpdatedRows:
      type: object
      properties:
        totalUpdatedRows:
          type: number
